global:
  kibanaCredEnabled: true
  elasticStorageManagement:
      policy: poc
  systemMode: ext-authz
  useNodePort: false
  image:
    pullPolicy: IfNotPresent
    registry: ${REGISTRY}
    version: ${VERSION}
  signaturesImage:
    registry: ${SIG_REGISTRY}
    version: ${SIG_VERSION}
  preserveJobs: false
  controller:
    serviceAppProtocol: grpc
  ratelimiter:
    serviceAppProtocol: grpc
  eventFetcher:
    serviceAppProtocol: http
  profilesCrud:
    serviceAppProtocol: http
  gui:
    serviceAppProtocol: https
  logstash:
    serviceAppProtocol: http

# TLS Settings - turn all TLS configurations other than
# elasticsearch, gui and validation controller off - 
# relying on istio mesh

waas-rate-limiter:
  tls:
    server:
      enabled: false
      mounts:
      volumes:
    clients:
      redis:
        enabled: off
        mounts:
        volumes:
      rateLimiter:
        enabled: off
        mounts:
        volumes:
      controller:
        enabled: off
        mounts:
        volumes:

waas-controller:
  tls:
    server:
      enabled: false
      mounts:
      volumes:
    clients:
      logagent:
        enabled: off
        mounts:
        volumes:
      nats:
        enabled: off
        mounts:
        volumes:
      rateLimiter:
        enabled: off
        mounts:
        volumes:

waas-enforcer:
  configType: mapping
  configName: waas-ext-auth-mapping
  configNamespace: ${APP_NS}
  tls:
    clients:
      logagent:
        logstash:
          enabled: off
          mounts:
          volumes:
        nats:
          enabled: false
          mounts:
          volumes:
      rateLimiter:
        enabled: off
        mounts:
        volumes:
      controller:
        enabled: off
        mounts:
        volumes:

waas-nats:
  tls:
    server:
      enabled: false
    clusters:
      enabled: false
    clients:
      enabled: false

waas-api-discovery:
  tls:
    clients:
      nats:
        enabled: false
      profilescrud:
        enabled: false

waas-events-fetcher:
  tls:
    server:
      enabled: false
      mounts:
      volumes:
    clients:
      eventsFetcher:
        enabled: false
        mounts:
        volumes:
      elasticsearch:
        verify: false

waas-gui:
  tls:
    server:
      enabled: true
      mounts:
        - name: gui-server-volume
          mountPath: /etc/gui/server
      # volume mounts containing certificates and keys
      volumes:
        - name: gui-server-volume
          secret:
            secretName: waas-gui-server-secret
    clients:
      eventsFetcher:
        enabled: false
        clientAuth: false
        mounts:
        volumes:
      profiles:
        enabled: false
        clientAuth: false
        mounts:
        volumes:

waas-logstash:
  enabled: true
  replicaCount: 1
  jvmMemorySize: 1000m
  batchSize: 100
  workers: 2
  tls:
    server:
      enabled: false
      mounts:
      volumes:
    clients:
      elasticsearch:
        verify: false
        mounts: 
        volumes: 

waas-profiles-crud:
  tls:
    server:
      enabled: false
      mounts:
      volumes:
    clients:
      profiles:
        enabled: false
        mounts:
        volumes:

waas-webddos:
  tls:
    clients:
      nats:
        enabled: false
        mounts:
        volumes:

waas-redis:
  tls:
    server:
      enabled: false
      mounts:
      volumes:
    clients:
      redis:
        enabled: false
        mounts:
        volumes:

waas-elasticsearch:
  enabled: true
  replicaCount: 1
  processors: 1
  persistentStorage:
    type: none # options for persistance storage types: kind, longhorn, azure/eks/gke
    size: 500Mi
  configureMmap: false
  tls:
    server:
      # transport TLS between elastic nodes
      transport:
        # NOTE all file locations are relative to ES_PATH_CONF
        # certificate file location, required
        certificate: "{{ .Values.ES_PATH_CONF }}/http/server/tls.crt"
        # key file location, required
        key: "{{ .Values.ES_PATH_CONF }}/http/server/tls.key"
        # ca certificate file location
        ca: "{{ .Values.ES_PATH_CONF }}/ca/ca.crt"
      # http TLS between elastic and users
      http:
        # NOTE all file locations are relative to ES_PATH_CONF
        # certificate file location, required
        certificate: "{{ .Values.ES_PATH_CONF }}/http/server/tls.crt"
        # key file location, required
        key: "{{ .Values.ES_PATH_CONF }}/http/server/tls.key"
        # ca certificate file location
        ca: "{{ .Values.ES_PATH_CONF }}/ca/ca.crt"
      mounts: |-
        # NOTE all mount paths must be under ES_PATH_CONF
        - name: ca-volume
          mountPath: "{{ .Values.ES_PATH_CONF }}/ca"
        - name: http-secret-server-volume
          mountPath: "{{ .Values.ES_PATH_CONF }}/http/server"
      # volume mounts containing certificates and keys
      volumes:
        - name: ca-volume
          configMap:
            name: waas-ca-config
        - name: http-secret-server-volume
          secret:
            secretName: waas-elasticsearch-exposed-server-secret

waas-validationcontroller:
  tls:
    server:
      enabled: true
      clientAuth: false
      certificate: /etc/validation-controller/server/tls.crt
      key: /etc/validation-controller/server/tls.key
      ca: /etc/validation-controller/ca/ca.crt
      verify: false
      mounts:
        - name: validation-controller-server-volume
          mountPath: /etc/validation-controller/server
        - name: ca-volume
          mountPath: /etc/validation-controller/ca
      # volume mounts containing certificates and keys
      volumes:
        - name: validation-controller-server-volume
          secret:
            secretName: waas-validation-controller-server-secret
        - name: ca-volume
          configMap:
            name: waas-ca-config
    webhook:
      caBundle: $(kubectl get cm waas-ca-config -n ${KWAAP_NS} -o go-template='{{index .data "ca.crt"}}' | base64 | tr -d \\n)
---
EOF
