kubectl apply -n test -f - <<-EOF
apiVersion: v1
data:
  admin_password: ZWNIMFdobGlFNkJ0c2ZrMVpndE42empN
  admin_user: bmF0cy1hZG1pbg==
  apidiscovery_password: Z1NCVmpzQWthSjdRTmp3MkNidEoxaGts
  apidiscovery_user: bmF0cy1hcGktZGlzY292ZXJ5
  controller_password: SUpjZHhYNzRjRW1ZSkI5bGZPNzBuM1BE
  controller_user: bmF0LWNvbnRyb2xsZXI=
  logagent_password: UVM0YWhqSXpiRW1ybWFZdHp5SGNuZTl3
  logagent_user: bmF0cy1sb2dhZ2VudA==
  webddos_password: dTBBTkpITFF5SkJhd0RUSzVONUZYZVFu
  webddos_user: bmF0cy13ZWJkZG9z
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: waas
    meta.helm.sh/release-namespace: kwaf
    waas.radware.com/pre-existing-secret: "false"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: waas-nats-users-secret
  namespace: test
type: Opaque
---
EOF
