name: KWAAP Deployment

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::714010226847:role/GitHubActionsDeployRole
          aws-region: ap-south-1

      - name: Verify AWS Authentication
        run: |
          aws sts get-caller-identity